### PR TITLE
Lots of name changes

### PR DESCRIPTION
**Pull request by IcarussOne**
This simple commit changes up several names of blocks, mobs, and items. Some typos were fixed up (e.g. silver kitty bed), and less generic and more spiced up names were given to make items and mobs stand out more and work better with other mods that add the exact same content, this includes creatures that were already added into vanilla Minecraft (and modern versions of it) such as horses, fish, goats, and bees.

<details>
<summary>Blocks</summary>

```
Ogre Lair Grass > Ogre Lair Grass Block
Ogre Lair Tall Grass > Ogre Lair Grass
Ogre Lair Wood Plank > Ogre Lair Wood Planks
Wyvern Lair Grass > Wyvern Lair Grass Block
Wyvern Lair Tall Grass > Wyvern Lair Grass
Wyvern Lair Wood Plank > Wyvern Lair Wood Planks
```
</details>

<details>

<summary>Items</summary>

```
Angelfish Egg > Koi Angelfish Egg
Angler Egg > Glowing Anglerfish Egg
Bass Egg > Smallmouth Bass Egg
Bo > Ninja Bo
Builder Hammer > Hammer of the Ancient Builders
Cave Scorpion Boots > Dark Chitin Boots
Cave Scorpion Egg > Dark Scorpion Egg
Cave Scorpion Helmet > Dark Chitin Helmet
Cave Scorpion Legs > Dark Chitin Leggings
Cave Scorpion Plate Chest > Dark Chitin Chestplate
Cave Scorpion Sting > Dark Scorpion Stinger
Cave Scorpion Sword > Dark Sting Blade
Clownfish Egg > Snowflake Clownfish Egg
Cobra Snake Egg > Cobra Egg
Cod Egg > Atlantic Cod Egg
Chitin Black > Dark Chitin
Chitin Frost > Frost Chitin
Chitin Nether > Hellfire Chitin
Dirt Scorpion Boots > Chitin Boots
Dirt Scorpion Helmet > Chitin Helmet
Dirt Scorpion Legs > Chitin Leggings
Dirt Scorpion Plate Chest > Chitin Chestplate
Dirt Scorpion Sting > Scorpion Stinger
Dirt Scorpion Sword > Sting Blade
Fish Net > Fishing Net
Frost Scorpion Boots > Frost Chitin Boots
Frost Scorpion Helmet > Frost Chitin Helmet
Frost Scorpion Legs > Frost Chitin Leggings
Frost Scorpion Plate Chest > Frost Chitin Chestplate
Frost Scorpion Sting > Frost Scorpion Stinger
Frost Scorpion Sword > Frost Sting Blade
Fur Helmet > Fur Hood
Fur Chest > Fur Tunic
Fur Legs > Fur Pants
Hay Stack > Haystack
Hide Boots > Hide Shoes
Hide Helmet > Hide Cap
Hide Chest > Hide Tunic
Hide Legs > Hide Thigh Guards
Hippotang Egg > Hippo Tang Egg
Katana > Ninja Katana
Manderin Egg > Mandarinfish Egg
Medallion > Name Medallion
Nether Scorpion Boots > Hellfire Chitin Boots
Nether Scorpion Egg > Hellfire Scorpion Egg
Nether Scorpion Helmet > Hellfire Chitin Helmet
Nether Scorpion Legs > Hellfire Chitin Leggings
Nether Scorpion Plate Chest > Hellfire Chitin Chestplate
Nether Scorpion Sting > Hellfire Scorpion Stinger
Nether Scorpion Sword > Hellfire Sting Blade
Nunchaku > Ninja Nunchaku
Omelet > Omelette (this is the more common spelling)
Piranha Egg > Red-Bellied Piranha Egg
Python Snake Egg > Python Egg
Rattle Snake Egg > Rattlesnake Egg
Reptile Boots > Reptile Hide Boots
Reptile Helmet > Reptile Hide Cap
Reptile Legs > Reptile Hide Pants
Reptile Plate > Reptile Hide Tunic
Sai > Ninja Sai
Salmon Egg > Atlantic Salmon Egg
Shark Sword > Leiomano (the name of the weapon it was based on)
Shark Teeth > Shark Tooth
Staff Teleport > Ancient Staff of Teleportation
Sugar Lump > Sugar Cubes
Silver Kitty Bed > Light Gray Kitty Bed
Silver Sword > Silver Blade
Wool Ball > Ball of Wool
Zebra Record > Zebra Music Disc
```
</details>

<details>

<summary>Mobs</summary>

```
Angelfish > Koi Angelfish (based on the real life species)
Angler > Glowing Anglerfish
Bass > Smallmouth Bass (based on the real life species)
Bee > Bumblebee
Big Golem > Block Golem
Black Bear > Wild Black Bear
Clownfish > Snowflake Clownfish (based on the real life species)
Cod > Atlantic Cod (based on the real life species)
Crab > Swimming Crab (they can't swim yet but this is the species that they most closely resemble)
Dolphin > Bottlenose Dolphin (based on the real life species)
Duck > Mallard Duck (based on the real life species)
Fire Ogre > Hellfire Ogre
Flame Wraith > Flaming Wraith
Fox > Ezo Fox (based on the real life Ezo Red Fox species)
Goat > Saanen Goat (based on the real life species)
Gold Fish > Goldfish
Green Ogre > Ogre
Grizzly Bear > Wild Grizzly Bear
Hippotang > Hippo Tang
Horse Mob > Nightmare (the fire horse has the same name but I thought it fitted the mob perfectly)
Manderin > Mandarinfish
Mini Golem > Mini Block Golem
Panda Bear > Wild Panda Bear
Piranha > Red-Bellied Piranha (based on the real life species)
Rat > Wild Rat
Salmon > Atlantic Salmon (based on the real life species)
Silver Skeleton > Skeleton Charger
Turkey > Wild Turkey (based on the real life species)
Wild Horse > Steed (other identical mobs to vanilla already have alternate names like Bunny or Kitty)
Wild Wolf > Vicious Wolf
Wraith > Ghostly Wraith
```
</details>

Hopefully this helps out, I had a lot of fun finding out the different species of animals that the creatures added by the mod resembled. :)

### CODE REVIEW

**Comment by IcarussOne** [comment]
Also included the french translation made by nocturni to address #12.

**Comment by IcarussOne** [comment]
Cleaned up the russian translation which had the entity entries under the wrong format, also removed unused entries and added missing entries.

**Comment by ACGaming** [comment]
Thanks for your efforts!
After careful consideration, we‘re going to revert some changes we deem unfitting or too intrusive. The detailed entity names are going to be part of an upcoming config option.

**Comment by IcarussOne** [comment]
Awesome! I had recent thoughts that some of the changes might be a bit much, if there's any changes you want me to make do let me know and I can fix them up, but it's fine if you want to instead do that yourself.

**Pull request merged**
